/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stablecoinSwitchSol from "./StablecoinSwitch.sol";
export type { stablecoinSwitchSol };
export type { MockERC20 } from "./MockERC20";
