[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true
gas_reports = ["*"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@arbitrum/=lib/arbitrum/",
    "@chainlink/=lib/chainlink-brownie-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Arbitrum One (Mainnet)
[rpc_endpoints]
arbitrum = "https://arb1.arbitrum.io/rpc"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
ethereum = "https://eth.llamarpc.com"
sepolia = "https://ethereum-sepolia.publicnode.com"

# Chain configurations
[etherscan]
arbitrum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
arbitrum_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Arbitrum-specific settings
[profile.arbitrum]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
optimizer = true
optimizer_runs = 1000  # Higher optimization for mainnet
via_ir = true
gas_reports = ["*"]
gas_limit = 30000000  # Arbitrum gas limit

# Test profile
[profile.test]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
optimizer = true
optimizer_runs = 200
verbosity = 2
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

