/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as stablecoinSwitchSol from "./StablecoinSwitch.sol";
export { MockERC20__factory } from "./MockERC20__factory";
